name: WAS

channels:
  - defaults

dependencies:
  - dgl-cu110==0.6.1
  - pyro-ppl==1.5.2 
  - python==3.7.13
  - torch==1.7.0+cu110
  - torchvision==0.8.1+cu110
  - torch-geometric==2.0.4
  - torch-scatter==2.0.7
  - torch-sparse==0.6.8
  - torch-spline-conv==1.2.1